### ISSUE TITLE
Breakdown Approach of Table 1.

### ISSUE THREAD

**Issue by RiweiPan** [yuhong-zhong/bpf-storage-hotos#1]
Hi, Yuhong. Thank you for your excellent works on the new gen NVMe SSDs. I learned a lot from your paper!

I'd like to reproduce the breakdown reuslts of Table 1 on my Optane 905 SSD to understand its I/O behaviours you introduced in the paper. Could you please tell me the approach to acquire the breakdown latencies in the different layer of the I/O stack? 

Thank you very much!
Riwei

**Comment by yuhong-zhong** [comment]
Sure. Our approach is instrumenting the kernel to take timestamps and calculate differences at all the layers. You can refer to [this kernel patch](https://gist.github.com/yuhong-zhong/d7d9077659246891cfc52f0d28e63298) to see how this is done.
